/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cup({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cup.geometry} material={materials['Material.002']} args={[10, 20, 30]} />
    </group>
  )
}

useGLTF.preload('./model.gltf')
